### ISSUE TITLE
crash on windows 10

### ISSUE THREAD

**Issue by 7u5a** [SuperFlyTV/SuperConductor#196] opened 2024-04-28 21:46 UTC
**Describe the bug**
Either casparcg og superconductor is crashing...

**To Reproduce**
Randomly when the program is open

**Expected behavior**
Should not crash

**Screenshots**
In the errorlog of windows I've found this:
Navn på program med fejl: SuperConductor.exe, version: 0.11.3.0, tidsstempel: 0x63754a68
Navn på modul med fejl: KERNELBASE.dll, version: 10.0.19041.4355, tidsstempel: 0xd7762934
Undtagelseskode: 0xc06d007e
Forskydning med fejl 0x000000000002ba99
Proces-id 0x1564
Programmets starttidspunkt 0x01da99940a8aecaa
Programsti: C:\Users\CasparCG\AppData\Local\Programs\superconductor\SuperConductor.exe
Modulsti: C:\Windows\System32\KERNELBASE.dll
Rapport-id: fd1343c1-c776-41ed-8030-36b1f146c0ca
Fuldt navn på program med fejl: 
Relativt program-id for program med fejl: 

and this one:
Navn på program med fejl: SuperConductor.exe, version: 0.11.3.0, tidsstempel: 0x63754a68
Navn på modul med fejl: ntdll.dll, version: 10.0.19041.4355, tidsstempel: 0x35a939aa
Undtagelseskode: 0xc0000409
Forskydning med fejl 0x00000000000a2420
Proces-id 0x1158
Programmets starttidspunkt 0x01da9989e3373d09
Programsti: C:\Users\CasparCG\AppData\Local\Programs\superconductor\SuperConductor.exe
Modulsti: C:\Windows\SYSTEM32\ntdll.dll
Rapport-id: c7972fb8-d125-46fe-b304-410673eab8d7
Fuldt navn på program med fejl: 
Relativt program-id for program med fejl: 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Also experience casparcg crash.:
Navn på program med fejl: casparcg.exe, version: 2.4.0.0, tidsstempel: 0x659dc181
Navn på modul med fejl: ntdll.dll, version: 10.0.19041.4355, tidsstempel: 0x35a939aa
Undtagelseskode: 0xc0000005
Forskydning med fejl 0x0000000000004408
Proces-id 0x3020
Programmets starttidspunkt 0x01da9993f9012b1b
Programsti: C:\casparcg-server-v2.4.0-rc1-windows\casparcg.exe
Modulsti: C:\Windows\SYSTEM32\ntdll.dll
Rapport-id: b77ac37f-a29f-404d-b7b8-d48688907c6f
Fuldt navn på program med fejl: 
Relativt program-id for program med fejl:

**Comment by nytamin** [comment] 2024-04-29 04:27
Thank you for this bug report.
From reading the logs and some googling, I don't think that the issue is with SuperConductor itself (especially since Casparcg crashed with the same error), but that it might be a corrupt driver, windows kernel or hardware issue on your computer.
If the problem persists, do a full clean reinstall of Windows and ensure you have the latest drivers installed. Running a disk check for faults might be a good idea as well.

I'll close this thread for now, but please leave a comment for posterity if you find something that helped with the issue.

**Closed by nytamin** 2024-04-29 04:27 UTC
Labels: bug

**Comment by 7u5a** [comment] 2024-05-02 02:36
Now the whole computer has been reinstalled.
Still SuperConductor comes with these error with KERNELBASE.dll and ntdll.dll

**Comment by nytamin** [comment] 2024-05-02 02:50
Thanks for taking the time to go through a reinstall, it's a bummer it didn't help..
I have no more ideas on how to troubleshoot further, unfortunately.

**Comment by 7u5a** [comment] 2024-05-06 04:57
After reinstalling the pc, windows and all drivers, it looks like, it's when opening the SuperConductor.
